apiVersion: "v1"
kind: "Service"
metadata:
  name: "hosted-danger"
  namespace: "default"
spec:
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 3001
  selector:
    app: "hosted-danger"
    tier: "api"
  type: "LoadBalancer"
  loadBalancerIP: ""